Library/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OperationsOnData.DAL;
using OperationsOnData.Models;
using OperationsOnData.Interfaces;
using Microsoft.AspNet.Identity;
using Library.ViewModels;

namespace Library.Controllers
{
    public class BooksController : Controller
    {
        private readonly IUserOperations userOperations;
        private readonly ISaveDatabase db;
        private readonly IBooksOperations bookOperations;

        public BooksController(IUserOperations userOpe, ISaveDatabase db, IBooksOperations booksOpe)
        {
            userOperations = userOpe;
            this.db = db;
            bookOperations = booksOpe;
        }

        public ActionResult Index()
        {
            if (bookOperations.GetBooks().Any(m => m.EndBookingDate < DateTime.Now))
            {
                var userId = User.Identity.GetUserId();
                userOperations.ResetBookingBooks(userId);
                db.SaveChanges();
            }

            if(bookOperations.GetBooks().Any(m => m.ReturnDate < DateTime.Now))
            {
                userOperations.SetObligation();
                db.SaveChanges();
            }            
            
            return View();
        }

        public ActionResult GetBooks()
        {
            var books = bookOperations.GetBooks();
            var booksVM = from book in books
                          select new ListOfBooksViewModel
                          {
                              Title = book.Title,
                              Type = book.Type,
                              Status = (Library.ViewModels.Status)book.Status,
                              Author = book.Author,
                              NumberOfPages = book.NumberOfPages,
                              BookId = book.BookId
                          };
            return Json(new { data = booksVM }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult ShowBookedBooks()
        {
            var userId = User.Identity.GetUserId();

            if (bookOperations.GetBooks().Any(m => m.EndBookingDate < DateTime.Now))
            {
                userOperations.ResetBookingBooks(userId);
                db.SaveChanges();
            }
            
            var books = bookOperations.GetBooks().Where(m => m.Status == OperationsOnData.Models.Status.Booked && m.UserId == userId);
            var booksVM = from book in books
                          select new BookedBookViewModel
                          {
                               BookId = book.BookId,
                               Author = book.Author,
                               Title = book.Title,
                               Status = (ViewModels.Status)book.Status,
                               Type = book.Type,
                               NumberOfPages = book.NumberOfPages,
                               BookingDate = book.BookingDate,
                               EndOfBookingDate = book.EndBookingDate
                          };
                
            return View(booksVM);
        }

        [Authorize]
        public ActionResult ShowBorrowedBooks()
        {
            if (bookOperations.GetBooks().Any(m => m.ReturnDate < DateTime.Now))
            {
                userOperations.SetObligation();
                db.SaveChanges();
            }
            var userId = User.Identity.GetUserId();
            var books = bookOperations.GetBooks().Where(m => m.Status == OperationsOnData.Models.Status.Borrowed && m.UserId == userId);
            var booksVM = from book in books
                          select new BorrowedBookViewModel
                          {
                              Title = book.Title,
                              Author = book.Author,
                              Status = (ViewModels.Status)book.Status,
                              Type = book.Type,
                              NumberOfPages = book.NumberOfPages,
                              BorrowingDate = book.BorrowingDate,
                              ReturnDate = book.ReturnDate
                          };
            return View(booksVM);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Reservation(int id)
        {
            var book = bookOperations.FindById(id);
            var userId = User.Identity.GetUserId();

            try
            {
                userOperations.Booking(book, userId);
                book.UserId = userId;
                db.SaveChanges();
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public ActionResult CancleReservation(int id)
        {
            var book = bookOperations.FindById(id);
            var userId = User.Identity.GetUserId();

            try
            {
                userOperations.CancleBooking(book, userId);
                book.UserId = null;
                db.SaveChanges();
            }
            catch
            {
                return View("Index");
            }

            return RedirectToAction("ShowBookedBooks");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Library/Views/Shared/_AboutSectionPartial.cshtml
<div class="heading-about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="wow bounceInLeft" data-wow-delay="0.3s">
                    <div class="section-heading">
                        <br /><br /><br /><br />
                        <h2>About Library</h2>
                        <i class="fa fa-2x fa-angle-down"></i>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-lg-2 col-lg-offset-5">
            <hr class="marginbot-50">
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-sm-3 col-md-12">
            <div class="wow bounceInLeft" data-wow-delay="0.3s">
                <div class="team">
                    <div class="inner">
                        <h5></h5>
                        <p class="subtitle">Our library is one of the largest libraries in the city. We have a large collection of books of various types. Each person will find something for themselves. We try to take care of our customers. We continually increase the volume of our books and try to ensure that all customers are satisfied with our services.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br /><br /><br /><br />

Library/Views/Shared/_BooksMainPanelPartial.cshtml
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/default.css" rel="stylesheet" />

<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container col-md-5">
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("All books", "Index", "Books")</li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Your books <span class="caret"></span> </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Booked books", "ShowBookedBooks", "Books")</li>
                            <li>@Html.ActionLink("Borrowed books", "ShowBorrowedBooks", "Books")</li>
                        </ul>
                    </li>
                }
            </ul>
        </div>
    </div>
    <div class="col-md-4">
        @Html.Partial("_LoginPartial")
    </div>
</nav>

Library/Views/Shared/_ContactSectionPartial.cshtml
<div class="heading-about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="wow bounceInLeft" data-wow-delay="0.3s">
                    <div class="section-heading">
                        <br /><br /><br /><br />
                        <h2>Contact</h2>
                        <i class="fa fa-2x fa-angle-down"></i>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">

    <div class="row">
        <div class="col-lg-2 col-lg-offset-5">
            <hr class="marginbot-50">
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-sm-3 col-md-12">
            <div class="wow bounceInLeft" data-wow-delay="0.3s">
                <div class="team">
                    <div class="inner">
                        <p><b>Email</b> - mateuszbedla@gmail.com</p>
                        <p class="subtitle"><b>Telephone number</b> - 606 189 121</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br /><br /><br /><br />

Library/Views/Shared/_HomeMainPanelPartial.cshtml
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/default.css" rel="stylesheet" />

<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container col-md-6">
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#intro">Home</a></li>
                <li><a href="#service">Services</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li>@Html.ActionLink("All books", "Index", "Books")</li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Your books <span class="caret"></span> </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Booked books", "ShowBookedBooks", "Books")</li>
                            <li>@Html.ActionLink("Borrowed books", "ShowBorrowedBooks", "Books")</li>
                        </ul>
                    </li>
                }
            </ul>
        </div>
    </div>
    <div class="container col-md-4">
        @Html.Partial("_LoginPartial")
    </div>
</nav>

Library/Views/Shared/_IntroSectionPartial.cshtml
<div class="slogan wow bounceInLeft" data-wow-delay="0.3s">
    <h2>WELCOME TO <span class="text_color">LIBRARY</span> </h2>
    <h4>THIS IS MYSTERIOUS PLACE WITH MANY ADEVENTURES</h4>
</div>
<div class="page-scroll">
    <a href="#service" class="btn btn-circle">
        <i class="fa fa-angle-double-down animated"></i>
    </a>
</div>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Library</title>

    @Styles.Render("~/Content/css")

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom">

    @RenderBody()
    <footer style="background-color:unset;">
        <p>
            <div class="container body-content" style="color:black;">
                &copy; @DateTime.Now.Year - Mateusz Bedła
            </div>
        </p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/myScripts")
    @RenderSection("scripts", required: false)

</body>
</html>

Library/Views/Shared/_ServicesSectionPartial.cshtml
<div class="heading-about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="wow bounceInLeft" data-wow-delay="0.3s">
                    <div class="section-heading">
                        <br /><br /><br /><br />
                        <h2>Our users can</h2>
                        <i class="fa fa-2x fa-angle-down"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-2 col-lg-offset-5">
            <hr class="marginbot-50">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 col-md-6">
            <div class="wow bounceInLeft" data-wow-delay="0.3s">
                <div class="service-box">
                    <div class="service-icon">
                    </div>
                    <div class="service-desc">
                        <h5>See all books in library</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 col-md-6">
            <div class="wow bounceInRight" data-wow-delay="0.3s">
                <div class="service-box">
                    <div class="service-icon">
                    </div>
                    <div class="service-desc">
                        <h5>Reserve available books</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 col-md-6">
            <div class="wow bounceInLeft" data-wow-delay="0.3s">
                <div class="service-box">
                    <div class="service-icon">
                    </div>
                    <div class="service-desc">
                        <h5>See all your booked books</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 col-md-6">
            <div class="wow bounceInRight" data-wow-delay="0.3s">
                <div class="service-box">
                    <div class="service-icon">
                    </div>
                    <div class="service-desc">
                        <h5>See all your borrowed books</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br /><br /><br /><br />