AdminApp/Controllers/AdminBooksController.cs
using AdminApp.ViewModels;
using Microsoft.AspNet.Identity;
using OperationsOnData.Interfaces;
using OperationsOnData.Models;
using ReportGenerator.Books;
using System;
using System.Linq;
using System.Web.Mvc;

namespace AdminApp.Controllers
{
    [Authorize]
    public class AdminBooksController : Controller
    {
        private readonly IUserOperations userOperations;
        private readonly ISaveDatabase db;
        private readonly IBooksOperations bookOperations;

        public AdminBooksController(IUserOperations userOpe, ISaveDatabase db, IBooksOperations booksOpe)
        {
            userOperations = userOpe;
            this.db = db;
            bookOperations = booksOpe;
        }

        public ActionResult Index()
        {
            if (bookOperations.GetBooks().Any(m => m.EndBookingDate < DateTime.Now))
            {
                var userId = User.Identity.GetUserId();
                userOperations.ResetBookingBooks(userId);
                db.SaveChanges();
            }

            return View();
        }

        public ActionResult GetBooks()
        {
            var books = bookOperations.GetBooks();
            return Json(new { data = books }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                bookOperations.RemoveBook(id);
                db.SaveChanges();
            }
            catch
            {
                return View("Index");
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookViewModel bookViewModel)
        {
            Book book = new Book {
                BookId = bookViewModel.BookId,
                Author = bookViewModel.Author,
                NumberOfPages = bookViewModel.NumberOfPages,
                Status = Status.Available,
                Title = bookViewModel.Title,
                Type = bookViewModel.Type };

            if (ModelState.IsValid)
            {
                bookOperations.AddBook(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(book);
        }

        public ActionResult Edit(int id)
        {
            var foundBook = bookOperations.FindById(id);
            BookViewModel bookVM = new BookViewModel {
                BookId = foundBook.BookId,
                Author = foundBook.Author,
                NumberOfPages = foundBook.NumberOfPages,
                Status = foundBook.Status,
                Title = foundBook.Title,
                Type = foundBook.Type };

            return View(bookVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BookViewModel bookViewModel)
        {
            Book book = new Book
            {
                BookId = bookViewModel.BookId,
                Author = bookViewModel.Author,
                Status = bookViewModel.Status,
                NumberOfPages = bookViewModel.NumberOfPages,
                Title = bookViewModel.Title,
                Type = bookViewModel.Type
            };

            if (ModelState.IsValid)
            {
                bookOperations.EditBook(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View(book);
        }

        public ActionResult GenerateReport()
        {
            var books = bookOperations.GetBooks().ToList();
            BooksReport report = new BooksReport();
            byte[] bytes = report.PrepareBooksReport(books);

            return File(bytes, "application/pdf");
        }
    }
}

AdminApp/Views/AdminBooks/Create.cshtml
@model AdminApp.ViewModels.BookViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Book</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NumberOfPages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" /> <br /><br />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminApp/Views/AdminBooks/Edit.cshtml
@model AdminApp.ViewModels.BookViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Book</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.BookId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>   

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NumberOfPages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" /> <br /><br />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminApp/Views/AdminBooks/Index.cshtml
@model IEnumerable<OperationsOnData.Models.Book>

@{
    ViewBag.Title = "Index";
}

<br /><br />
<div class="panel panel-default">
    <div class="panel-heading">
        <span>
            <h3>All Books</h3>
        </span>
    </div>
    <div class="panel-body">
        <div>
            <p>@Html.ActionLink("Add book to database", "Create", "AdminBooks", null, new { @class = "btn btn-primary" })</p>
        </div>
        <div>
            <p>@Html.ActionLink("Generate report", "GenerateReport", "AdminBooks", null, new { @class = "btn btn-primary" })</p>
        </div>
        <div style="width:90%; margin:0 auto;">
            <table id="myTable" class="table table-bordered table-responsive table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Type</th>
                        <th>Pages</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>


<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script>
        function RenderHTMLActionButtons(id)
        {
            return `<center><a class="btn btn-primary" href= "@Html.Raw(HttpUtility.UrlDecode(Url.Action("Edit", "AdminBooks", new { id = "{{id}}" })))">
                        Edit
                    </a> | 
                    <form action="@Html.Raw(HttpUtility.UrlDecode(Url.Action("Delete", "AdminBooks", new { id = "{{id}}" })))" method="post">
                        <input type="submit" value="Delete" onclick="return confirm('Are you sure?')" class="btn btn-danger">
                    </form></center>`
            .replace(/{{id}}/g, id);
    }

    $(document).ready(function () {
        var oTable = $('#myTable').DataTable({
            "ajax": {
                "url": '/AdminBooks/GetBooks',
                "type": "get",
                "datatype": "json"
            },
            "columns": [
                { "data": "Title", "autoWidth": true },
                { "data": "Author", "autoWidth": true },
                { "data": "Type", "autoWidth": true },
                { "data": "NumberOfPages", "autoWidth": true },
                { "data": "Status", "autoWidth": true },
                {
                    "title": '',
                    "data": null,
                    "render": function (data, type, row) {

                        return RenderHTMLActionButtons(data['BookId']);
                    }
                }
            ],
            "columnDefs": [{
                "targets": 4,
                "render": function (data) {
                    switch (data) {
                        case 1: return "Available";
                        case 2: return "Borrowed";
                        case 0: return "Booked";
                    }
                }
            }]
        })


    })
</script>

<style>
    form{
        display: inline-block;
    }
</style>